### ISSUE TITLE
No Reply From Target

### ISSUE THREAD

**Issue by zharris6** [ThrDev/Socks5#15] opened 2016-11-15 20:17 UTC
Hello - 

I have implemented the Socks5Client instance and connected with no issue.

Once the client is connected, I send a couple of byes and wait for a reply (like below)

I am doing a TCPDump on the target server, and i see the bytes getting sent fine...However, No matter what i do, the response is always null. 

Am I doing something wrong?

```
               byte[] sendBuf = System.Text.ASCIIEncoding.ASCII.GetBytes("GET \n");

                byte[] recvBuf = new byte[1024];

                client.Client.Send(sendBuf, 0, sendBuf.Length);            

                int receivedDataLength = client.Client.Receive(recvBuf, 0, recvBuf.Length);
```

**Comment by ThrDev** [comment] 2016-11-15 22:04
Hey zharris6,

I realize I don't have any documentation on any of this, especially the socks5 client. Here's some insights on how to use it:

https://github.com/ThrDev/Socks5/blob/master/socks5/socks5/Socks5Client/Socks5Client.cs

You should be able to add handlers for callbacks, such as:

```
...
client.OnDataReceived += Client_onDataReceived;
client.ReceiveAsync();
...

void Client_onDataReceived(object sender, Socks5ClientDataArgs e) {
     // The data should be located in e.Buffer
}
```

Now, this assumes where your example says

```
client.Client.Send(....)
```

Is "client" the Socks5Client or is "Client" the Socks5Client?

The example above assumes "client" is an instance of the Socks5Client.

The Socks5Client.Client property is for raw access to the sockets. If you just replace "client.Client" with "client", you should be able to use your code again properly (if you aren't looking to use event handlers).

**Comment by zharris6** [comment] 2016-11-15 22:10
Thank you ThrDev for the quick reply. I am having a hell of a time trying to wire up a Socks5 proxy to my FTP client and this may help. 

I really appreciate it!!

**Comment by ThrDev** [comment] 2016-11-15 22:13
Not a problem! Glad to be a help!

Also, I might have misunderstood your question. When you are sending HTTP GET requests, you'll have to send a proper request, as it may be denying your request because of the invalid headers.

```
byte[] myRequest = Encoding.ASCII.GetBytes("GET / HTTP/1.1\r\n\r\n");
```

**Comment by zharris6** [comment] 2016-11-15 22:18
Well I really did that as a test, just to see if I get anything back.

I am really trying to wire up your package with this:

https://github.com/hgupta9/FluentFTP

The connection keeps closing and every reply is null.

That is the real crux of my issues :).

Thanks again for your support.

**Comment by zharris6** [comment] 2016-11-15 22:49
I may be missing something. I wired it up like you suggested and the callback never fires. Here is my code. 

I can confirm via a TCPDump on the target, that the request is in fact getting there and it is returning a response. It is just not getting picked up by the CallBack.


   ```
 private void Client_onDataReceived(object sender, Socks5ClientDataArgs e)
        {
            var test = e.Buffer;
        }

        private void Proxy()
        {
            Socks5Client client = new Socks5Client(ProxyHost, 8437, TargetIp, TargetPort, ProxyUser, ProxyPass);
            client.OnDataReceived += Client_onDataReceived;

            client.Connect();

            if (client.Connected)
            {
                byte[] myRequest = Encoding.ASCII.GetBytes("GET / HTTP/1.1\r\n\r\n");

                byte[] recvBuf = new byte[1024];

                client.ReceiveAsync();
                client.Send(myRequest, 0, myRequest.Length);

                Console.Out.WriteLine(System.Text.ASCIIEncoding.ASCII.GetString(recvBuf));
            }
```

**Comment by ThrDev** [comment] 2016-11-16 15:10
Hey again,

That was my bad. I thought you were talking about HTTP requests before you posted about connecting to an FTP server.

It seems as if the connect() function is not working as intended. To alleviate this problem, ConnectAsync() should work.

```
...
private static void Client_onDataReceived(object sender, Socks5ClientDataArgs e)
{
	Console.WriteLine (System.Text.ASCIIEncoding.ASCII.GetString (e.Buffer));
}

private static void Client_onConnected(object sender, Socks5ClientArgs e)
{
		Console.WriteLine("Connected.");

		client.ReceiveAsync ();

		byte[] myRequest = System.Text.Encoding.ASCII.GetBytes ("GET \n");
		client.Send (myRequest, 0, myRequest.Length);
}

private static void Proxy()
{
	Socks5Client client = new Socks5Client ("localhost", 20202, "localhost", 21);
	client.OnDataReceived += Client_onDataReceived;
	client.OnConnected += Client_onConnected;
	client.ConnectAsync();
}
...
```

Or, if you prefer lambdas, you can declare OnConnected like the following:

```
client.OnConnected += (object sender, Socks5ClientArgs e) => {
	Console.WriteLine("Connected.");
	client.ReceiveAsync ();
	byte[] myRequest = System.Text.Encoding.ASCII.GetBytes ("GET \n");
	client.Send (myRequest, 0, myRequest.Length);
};
```

I hope this helps! I tested this and got the following output:

```
localhost:21
Connected.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 50 allowed.
220-Local time is now 10:10. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
```

**Comment by ThrDev** [comment] 2016-11-16 15:17
Also note, as I missed before, you should call e.Client.ReceiveAsync() after you do what you need in Client_onDataReceived(..) - This assures that it will attempt to receive again, and it won't fire the event until there is data waiting to be received.

**Comment by zharris6** [comment] 2016-11-16 22:53
Thanks for taking the time to write examples. I think i am in over my head. I was able to get the connect callback to fire, but the onDataReceive callback never does. If I cant figure out this small example I doubt I am going to be able to wire it to FluentFtp.

Here is my code in case your curious
```

        private static void Client_onDataReceived(object sender, Socks5ClientDataArgs e)
        {
            Console.WriteLine(System.Text.ASCIIEncoding.ASCII.GetString(e.Buffer));
        }


        private void Proxy()
        {
            
                Socks5Client client = new Socks5Client(ProxyHost, 8437, TargetIp, TargetPort, ProxyUser, ProxyPass);

                 
                client.OnDataReceived += Client_onDataReceived;
                client.OnConnected += (object sender, Socks5ClientArgs e) =>
                {
                    Console.WriteLine("Connected.");
                    isconnected = true;
                    client.ReceiveAsync();
                    byte[] myRequest = System.Text.Encoding.ASCII.GetBytes("GET \n");
                    client.Send(myRequest, 0, myRequest.Length);
                    
                };
                client.ConnectAsync();
                while (!endcall)
                {
                }

       
        }
```

**Comment by ThrDev** [comment] 2016-11-17 14:21
Hey again zharris6,

Could you do me a favor and check the Socks5ClientArgs variable named Status?

In your OnConnected Code:

```
...
client.OnConnected += (object sender, Socks5ClientArgs e) =>
{
     if(e.Status == SocksError.Failure) {
          Console.WriteLine("Failed to connect.");
     }
     else {
          Console.WriteLine("Connected.");
          isconnected = true;
          client.ReceiveAsync();
          byte[] myRequest = System.Text.Encoding.ASCII.GetBytes("GET \n");
          client.Send(myRequest, 0, myRequest.Length);
     }
};
...
```

**Comment by zharris6** [comment] 2016-11-17 14:26
I just added your code, The Console Writes “Connected” and never hits the Failed To Connect Line.

 

Same issues as before, It connects fine, Sends the data (confirmed via a TCP Dump on Target), then the OnClientDisconnect callback instantly fires (before the data can be received, confirmed I get data back via wireshark).

**Comment by ThrDev** [comment] 2016-11-17 14:45
I've added some changes to Socks5Client.cs. If there are any errors, they will now be thrown. If you are using Visual Studio, there should be an option under the Debug menu called "Exceptions". If you could select .net exceptions "throw" or something to that effect, it should show you any thrown exceptions.

I don't have Visual Studio in front of me so I don't remember exactly what the items were called.

**Comment by zharris6** [comment] 2016-11-17 14:57
ThrDev - Thanks for your continued support.

I Pulled Your changes, and Made sure my debug window was showing thrown exceptions, and there is nothing :(

The program starts, Connects, Sends the packet, Then instantly disconnects.

I even added the ManualResetEvent instance to make sure the program is in fact pausing and waiting for a response.

It gets through the connection and send packet events fine, It waits for a response for the onDataReceived event, but it never gets anything.

The client still instantly disconnects after the packet is sent.

**Comment by ThrDev** [comment] 2016-11-17 15:12
I wonder if the FTP server is closing your connection... That's interesting. Is there any other possible way you could try attempting to connect to a different FTP server?

**Comment by zharris6** [comment] 2016-11-17 15:29
I tried a windows based FileZilla server and its the same result. However i am noticing something weird in the Wireshark dump.

Right after the GET packet is sent, a Red packet is sent back. Which tells me the client sent an ABORT or RESET packet (i think)

![capture](https://cloud.githubusercontent.com/assets/6600305/20395368/af28d472-acb0-11e6-807e-ec500dadd64e.PNG)

**Comment by ThrDev** [comment] 2016-11-17 15:46
Does the FTP server have authentication turned on? As far as I know, I would think that you would have to send some type of authentication even if it's anonymous.

Lastly, try changing 'GET' to 'ls', maybe that would help. I think GET requires an argument.
https://www.cs.colostate.edu/helpdocs/ftp.html

**Comment by zharris6** [comment] 2016-11-17 20:57
I solved the problem!!!

Thank you 100X for all your support. If there is anything I can help you with, and return the favor, please let me know.

For the record, all it was, that the FTP firewall wasn't allowing my proxy IP through to connect.

Sometimes the answer is right in front of you :(

At least i learned alot!! 

Cheers m8!

**Closed** 2016-11-17 22:16 UTC
Labels: question
